services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Nospecialcharacters
      POSTGRES_DB: gaming
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: game_reviews
